package com.xzd1314.aichat.ui.screens

/** 开发历程：真实操作记录（时间来自执行日志与文件时间戳） */
data class DevStep(val time: String, val title: String, val detail: String)

object DevTimeline {
    val steps: List<DevStep> = listOf(
        DevStep("02:5x", "检测构建环境",
            "系统仅安装 OpenJDK 11，无 Android SDK、无 Gradle，无任何构建工具链"),
        DevStep("02:52", "下载 Android SDK 命令行工具",
            "从 dl.google.com 拉取 commandlinetools-linux-11076708_latest.zip，解压至 ~/android-sdk/cmdline-tools/latest"),
        DevStep("02:5x", "首次运行 sdkmanager 报错",
            "LinkageError：SdkManagerCli 编译于 Java 61（Java 17），当前 JVM 仅支持到 55（Java 11），判定需升级 JDK"),
        DevStep("03:33", "下载 OpenJDK 17.0.2",
            "apt 安装因容器权限失败，改为从 download.java.net 拉取免安装发行版 openjdk-17.0.2_linux-x64_bin.tar.gz"),
        DevStep("03:34", "解压并验证 JDK 17",
            "解压至 ~/jdk-17.0.2，java -version 输出 17.0.2 2022-01-18，构建工具链就绪"),
        DevStep("03:35:21", "安装 Android SDK 组件",
            "接受全部许可，安装 platform-tools（adb）、build-tools;35.0.0（aapt2/d8）、platforms;android-35"),
        DevStep("03:35:30", "SDK 组件安装完成",
            "platforms/android-34 与 android-35、build-tools 34/35 全部就位，adb/fastboot 可用"),
        DevStep("03:35:36", "创建工程目录",
            "建立 apk_src/（Gradle 工程根）与 Assets/（素材目录）"),
        DevStep("03:36", "头像抠图（两轮迭代）",
            "第一轮 flood-fill 去白底误删角色主体（仅剩 8.4% 像素）；第二轮改用 OpenCV GrabCut 分割成功（保留 49.7%），输出透明 PNG + 512 方形版本"),
        DevStep("03:38", "下载 Gradle 8.9",
            "从 services.gradle.org 拉取 gradle-8.9-bin.zip 并解压至 ~/gradle-8.9，构建时将指定 JAVA_HOME=JDK17"),
        DevStep("03:39", "编写 Gradle 工程配置",
            "AGP 8.6.1 + Kotlin 1.9.24 + Compose BOM 2024.06.00 + Material3，minSdk 26 / targetSdk 35（Android 15），关闭 minify 于 debug"),
        DevStep("03:41", "数据层",
            "会话/消息/风格模型 + 13 家国内大模型供应商预设（DeepSeek/GLM/Kimi/Qwen/豆包/文心/星火/混元…），SharedPreferences + JSON 持久化"),
        DevStep("03:43", "网络层 LLMClient",
            "HttpURLConnection 封装 OpenAI 兼容端点；缓存命中优化：固定 system 前缀、确定性序列化、尾部截断、无动态字段；token 估算与连接测试"),
        DevStep("03:45", "主题与通用组件",
            "Material3 双色主题（深海蓝+星紫）、圆形头像（URI 异步加载）、色板+RGB 滑块颜色选择器、风格驱动气泡组件"),
        DevStep("03:47", "对话列表页",
            "搜索过滤、新增/删除会话（确认弹窗）、最后消息摘要、空状态插画、Material3 卡片列表"),
        DevStep("03:50", "聊天窗",
            "右上三点菜单：会话设置（改名/换头像）、聊天风格、模型与上下文信息、清空、删除；自动滚底、打字指示器、错误提示"),
        DevStep("03:53", "风格编辑器",
            "30 套预设（微信/QQ/X/iMessage/Telegram/WhatsApp/Discord/钉钉/企业微信/Slack/B站/小红书/微博/知乎/抖音/终端/像素/极简/暗黑/赛博朋克/少女粉/黑金/护眼绿/纸质/霓虹…）+ 自定义编辑 + 实时预览 + 分享文本（XZD-STYLE:v1. base64）复制导出/剪贴板导入"),
        DevStep("03:56", "设置页",
            "供应商切换（含自定义 OpenAI 兼容）、API Key/模型名/Base URL、测试连接、上下文条数/最大 Token/温度滑块、系统提示词、缓存命中优化开关、使用统计"),
        DevStep("03:58", "关于页",
            "圆形头像（抠图版）、昵称 xzd1314、网站 xzd1314.top（点击跳转系统浏览器）、本开发历程时间线、版本信息"),
        DevStep("04:0x", "v1.0.0 构建与验证",
            "Gradle assembleDebug → 修复6处编译问题 → release构建 → APK签名 → aapt2/签名校验 → 交付 v1.0.0（10.4MB）"),
        DevStep("v1.1", "正式签名与混淆",
            "keytool生成RSA2048正式keystore（10000天）；v1/v2/v3签名；isMinifyEnabled+isShrinkResources；proguard混淆-repackageclasses/移除Log；APK从10.4MB缩至6.3MB"),
        DevStep("v1.1", "高级配色与新图标",
            "深墨绿(#1B4332)+古铜金(#C9A961)+暖米白(#FAF6EE)奢华复古风；adaptive icon重绘：墨绿背景+金色气泡+X字母+三点"),
        DevStep("v1.1", "全局UI动画",
            "tab切换AnimatedContent（淡入+水平滑动300ms）；气泡进入动画（alpha+translationY 350ms）；思考块展开箭头rotate动画"),
        DevStep("v1.1", "思考模式",
            "ChatMessage加reasoning字段；LLMClient传reasoning_effort解析reasoning_content；设置页4档（关闭/低/中/高）；聊天中可折叠思考块"),
        DevStep("v1.1", "Agent模式",
            "ShellExecutor：Root(su)/Shizuku(反射)/普通三模式自动降级；AgentScreen：权限徽章、命令块解析执行、结果回显；底部导航新增第4个Agent tab"),
        DevStep("v1.1", "v1.1.0 构建交付",
            "修复编译错误；clean rebuild成功；jarsigner确认v1+apksigner确认v2/v3；交付 v1.1.0（6.3MB）")
    )
}
